"""Tooling commands -- gen-runner, patch, unpatch, merge."""

import logging
import os
import sys

from ..core import _log_ok, _log_err, _log_info, _log_warn, _opt
from ...base import CmdContext

log = logging.getLogger(__name__)


def _extract_package_name(input_path):
    """Extract package name from split APK directory.

    Uses the base APK filename (the one not starting with 'split_').
    e.g. 'com.niceid.nicemypin.apk' -> 'com.niceid.nicemypin'
    Returns package name string or None.
    """
    if os.path.isdir(input_path):
        apks = [f for f in os.listdir(input_path) if f.lower().endswith(".apk")]
        base_apks = [f for f in apks if not f.lower().startswith("split_")]
        if base_apks:
            # base APK filename is typically the package name
            return os.path.splitext(base_apks[0])[0]
    elif os.path.isfile(input_path):
        return os.path.splitext(os.path.basename(input_path))[0]
    return None


def _java_tools(config):
    """Resolve java/javac/jar binary paths from config."""
    java_home = config["jeb"].get("java_home")
    if java_home:
        return (os.path.join(java_home, "bin", "java"),
                os.path.join(java_home, "bin", "javac"),
                os.path.join(java_home, "bin", "jar"),
                os.path.join(java_home, "bin", "javap"))
    return ("java", "javac", "jar", "javap")


def _resolve_apkeditor(config):
    """Resolve APKEditor JAR path from config or default location.

    Search order:
        1. config["tools"]["apkeditor"] (absolute or relative to project root)
        2. tools/libs/APKEditor-*.jar (auto-detect)
    """
    jar = config.get("tools", {}).get("apkeditor", "")

    # __file__ = revkit/tools/engines/jeb/commands/tooling.py
    # → commands → jeb → engines → tools (4 levels up)
    tools_dir = os.path.abspath(__file__)
    for _ in range(4):
        tools_dir = os.path.dirname(tools_dir)

    if jar:
        if not os.path.isabs(jar):
            # Resolve relative to project root (2 levels above tools/)
            project_root = os.path.dirname(os.path.dirname(tools_dir))
            jar = os.path.join(project_root, jar)
    else:
        # Auto-detect from tools/libs/
        import glob
        candidates = sorted(glob.glob(os.path.join(tools_dir, "libs", "APKEditor-*.jar")))
        jar = candidates[-1] if candidates else ""

    if not jar or not os.path.isfile(jar):
        _log_err(f"APKEditor JAR not found: {jar or 'tools/libs/APKEditor-*.jar'}")
        _log_info("Download: gh release download V1.4.7 --repo REAndroid/APKEditor --dir revkit/tools/libs/")
        return None, None

    java_home = config["jeb"].get("java_home")
    java_path = os.path.join(java_home, "bin", "java") if java_home else "java"

    return jar, java_path


def _is_jar_patched(jeb_dir):
    """Check if Launcher.class has --script= support (patched or native)."""
    import zipfile
    jar_path = os.path.join(jeb_dir, "bin", "app", "jeb.jar")
    try:
        with zipfile.ZipFile(jar_path) as zf:
            data = zf.read("com/pnfsoftware/jeb/Launcher.class")
            return b"--script=" in data
    except Exception as _e:
        log.warning("_is_jar_patched: failed to check jeb.jar: %s", _e)
        return False


# =============================================================
# gen-runner: Auto-generate JebScriptRunner.java
# =============================================================

_RUNNER_TEMPLATE = '''\
import com.pnfsoftware.jeb.{cls};
import java.util.Arrays;

/**
 * JEB {ver} Headless Script Runner - bypasses Launcher.main() and invokes {cls} directly.
 * Auto-generated by: jeb-cli gen-runner
 * Usage: java [JVM opts] -cp "bin/app/*;." JebScriptRunner <script_path> [-- extra_args...]
 */
public class JebScriptRunner {{
    public static void main(String[] args) throws Exception {{
        if (args.length < 1) {{
            System.err.println("Usage: JebScriptRunner <script_path> [-- extra_args...]");
            System.exit(1);
        }}

        String scriptPath = args[0];
        String libDir = null;

        // collect extra args after "--"
        String[] extraArgs = new String[0];
        for (int i = 1; i < args.length; i++) {{
            if ("--".equals(args[i])) {{
                if (i + 1 < args.length) {{
                    extraArgs = Arrays.copyOfRange(args, i + 1, args.length);
                }}
                break;
            }}
        }}

        {cls} runner = new {cls}(false, scriptPath, libDir, extraArgs);
        runner.initialize(new String[]{{}});
        runner.start();
        runner.stop();
    }}
}}
'''


def _find_runner_class(jeb_dir, config):
    """Scan jeb.jar for the HeadlessClientContext script runner class.

    Returns (class_short_name, jeb_version_string) or (None, None).
    """
    import subprocess as sp
    import re

    jar_path = os.path.join(jeb_dir, "bin", "app", "jeb.jar")
    if not os.path.isfile(jar_path):
        _log_err(f"jeb.jar not found: {jar_path}")
        return None, None

    _, _, jar_bin, javap_bin = _java_tools(config)

    # Step 1: list classes in com/pnfsoftware/jeb/ (top-level only, short names)
    _log_info("Scanning jeb.jar for script runner class...")
    try:
        out = sp.check_output([jar_bin, "tf", jar_path],
                              stderr=sp.DEVNULL, text=True, timeout=30)
    except FileNotFoundError:
        _log_err(f"jar not found: {jar_bin}")
        _log_info("Set jeb.java_home in config.json or add Java JDK to PATH")
        return None, None
    except Exception as e:
        _log_err(f"jar tf failed: {e}")
        return None, None

    # Candidates: com/pnfsoftware/jeb/XX.class where XX is 1-3 chars (obfuscated)
    candidates = []
    for line in out.splitlines():
        line = line.strip()
        if not line.startswith("com/pnfsoftware/jeb/"):
            continue
        if line.count("/") != 3:  # exactly com/pnfsoftware/jeb/XX.class
            continue
        if not line.endswith(".class"):
            continue
        name = line.rsplit("/", 1)[1].replace(".class", "")
        if len(name) <= 3 and not name.startswith("$"):
            candidates.append(name)

    if not candidates:
        _log_err("No short-named candidate classes found in com.pnfsoftware.jeb")
        return None, None

    _log_info(f"Found {len(candidates)} candidates: {', '.join(sorted(candidates))}")

    # Step 2: javap each candidate to find HeadlessClientContext subclass
    cp = jar_path
    found = None
    for name in sorted(candidates):
        fqn = f"com.pnfsoftware.jeb.{name}"
        try:
            jout = sp.check_output(
                [javap_bin, "-cp", cp, "-public", fqn],
                stderr=sp.DEVNULL, text=True, timeout=15)
        except Exception:
            continue

        # Check: extends HeadlessClientContext AND has (boolean, String, String, String[])
        if "HeadlessClientContext" not in jout:
            continue
        if re.search(r"(boolean,\s*java\.lang\.String,\s*java\.lang\.String,\s*java\.lang\.String\[\])", jout):
            found = name
            _log_ok(f"Found script runner class: {fqn}")
            break

    if not found:
        _log_err("Could not find HeadlessClientContext subclass with expected constructor")
        _log_info("Known classes: JM (5.38), bC (5.37), Om (5.36)")
        return None, None

    # Step 3: try to get JEB version from Launcher
    version = "unknown"
    try:
        lout = sp.check_output(
            [javap_bin, "-cp", cp, "-constants", "com.pnfsoftware.jeb.Launcher"],
            stderr=sp.DEVNULL, text=True, timeout=15)
        # Look for version string like "5.38.0" in constant pool
        ver_match = re.search(r'(\d+\.\d+\.\d+\.\d+)', lout)
        if ver_match:
            version = ver_match.group(1)
        else:
            ver_match = re.search(r'(\d+\.\d+\.\d+)', lout)
            if ver_match:
                version = ver_match.group(1)
    except Exception as _e:
        log.warning("_find_runner_class: failed to detect JEB version: %s", _e)

    return found, version


def cmd_gen_runner(ctx: CmdContext):
    """Auto-detect script runner class and generate JebScriptRunner.java."""
    args, config = ctx.args, ctx.config
    jeb_dir = config.get("jeb", {}).get("install_dir", "")
    log.debug("cmd_gen_runner: jeb_dir=%s", jeb_dir)
    if not os.path.isdir(jeb_dir):
        _log_err(f"JEB install directory not found: {jeb_dir}")
        return

    cls_name, jeb_ver = _find_runner_class(jeb_dir, config)
    if not cls_name:
        return

    runner_path = os.path.join(jeb_dir, "JebScriptRunner.java")
    if os.path.isfile(runner_path):
        with open(runner_path, "r", encoding="utf-8") as f:
            existing = f.read()
        if f"import com.pnfsoftware.jeb.{cls_name};" in existing:
            if not _opt(args, 'force', False):
                _log_ok(f"JebScriptRunner.java already uses {cls_name} - up to date")
                _log_info("Use --force to regenerate")
                return

    source = _RUNNER_TEMPLATE.format(cls=cls_name, ver=jeb_ver)
    with open(runner_path, "w", encoding="utf-8") as f:
        f.write(source)
    _log_ok(f"Generated: {runner_path}")
    _log_info(f"  Runner class: com.pnfsoftware.jeb.{cls_name}")
    _log_info(f"  JEB version:  {jeb_ver}")

    project_runner = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "jeb-runner", "JebScriptRunner.java")
    if os.path.isdir(os.path.dirname(project_runner)):
        with open(project_runner, "w", encoding="utf-8") as f:
            f.write(source)
        _log_ok(f"Updated project copy: {project_runner}")

    if _opt(args, 'no_compile', False):
        _log_info("Skipping compilation (--no-compile)")
        return

    _log_info("Compiling JebScriptRunner.java...")
    import subprocess as sp
    _, javac_bin, _, _ = _java_tools(config)
    cp = os.path.join(jeb_dir, "bin", "app", "*")

    try:
        sp.check_call(
            [javac_bin, "-cp", cp, "JebScriptRunner.java"],
            cwd=jeb_dir, timeout=60,
            stdout=sp.DEVNULL, stderr=sp.PIPE)
        class_path = os.path.join(jeb_dir, "JebScriptRunner.class")
        if os.path.isfile(class_path):
            _log_ok(f"Compiled: {class_path}")
            # Copy .class to project
            project_class = os.path.join(os.path.dirname(project_runner), "JebScriptRunner.class")
            if os.path.isdir(os.path.dirname(project_class)):
                import shutil
                shutil.copy2(class_path, project_class)
        else:
            _log_warn("javac succeeded but .class file not found")
    except sp.CalledProcessError as e:
        _log_err(f"Compilation failed: {e.stderr.decode() if e.stderr else 'unknown error'}")
        _log_info("Fix errors and compile manually:")
        _log_info(f'  cd {jeb_dir} && javac -cp "bin/app/*" JebScriptRunner.java')
    except FileNotFoundError:
        _log_err(f"javac not found: {javac_bin}")
        _log_info("Set jeb.java_home in config.json or add Java to PATH")


# =============================================================
# LauncherPatcher template
# =============================================================

_PATCHER_TEMPLATE = '''\
import net.bytebuddy.jar.asm.*;
import static net.bytebuddy.jar.asm.Opcodes.*;

/**
 * Patches Launcher.class to restore --script= argument handling.
 * Auto-generated for JEB {ver} (runner class: {cls})
 *
 * Strategy:
 *   Inject --script= / --libdir= handling at the start of main().
 *   - Found: create {cls}, run script, return.
 *   - Not found: fall through to original main() code (100% unchanged).
 *   No method renaming. Original main() bytecode is fully preserved.
 */
public class LauncherPatcher {{
    public static void main(String[] args) throws Exception {{
        java.util.jar.JarFile jar = new java.util.jar.JarFile("bin/app/jeb.jar");
        java.util.jar.JarEntry entry = jar.getJarEntry("com/pnfsoftware/jeb/Launcher.class");
        byte[] original;
        try (java.io.InputStream is = jar.getInputStream(entry)) {{
            original = is.readAllBytes();
        }}
        jar.close();
        System.out.println("[*] Read Launcher.class: " + original.length + " bytes");

        ClassReader cr = new ClassReader(original);
        ClassWriter cw = new ClassWriter(cr, ClassWriter.COMPUTE_FRAMES) {{
            @Override
            protected String getCommonSuperClass(String type1, String type2) {{
                return "java/lang/Object";
            }}
        }};

        cr.accept(new ClassVisitor(ASM9, cw) {{
            @Override
            public MethodVisitor visitMethod(int access, String name, String desc,
                                             String signature, String[] exceptions) {{
                MethodVisitor mv = super.visitMethod(access, name, desc, signature, exceptions);
                if ("main".equals(name) && "([Ljava/lang/String;)V".equals(desc)) {{
                    System.out.println("[*] Injecting --script= handling into main()");
                    return new MethodVisitor(ASM9, mv) {{
                        @Override
                        public void visitCode() {{
                            super.visitCode();
                            injectScriptCheck(mv);
                        }}
                    }};
                }}
                return mv;
            }}
        }}, 0);

        byte[] patched = cw.toByteArray();
        java.io.File outDir = new java.io.File("patch_out/com/pnfsoftware/jeb");
        outDir.mkdirs();
        java.io.File outFile = new java.io.File(outDir, "Launcher.class");
        java.nio.file.Files.write(outFile.toPath(), patched);
        System.out.println("[+] Patched Launcher.class: " + patched.length + " bytes -> " + outFile);
    }}

    /**
     * Inject at the start of main():
     *   1. Scan args for --script= and --libdir=
     *   2. If --script= found -> create {cls}, run, return
     *   3. If not found -> fall through to original main() code
     */
    private static void injectScriptCheck(MethodVisitor mv) {{
        Label originalStart = new Label();

        // Scan args for --script= and --libdir=
        mv.visitInsn(ACONST_NULL);
        mv.visitVarInsn(ASTORE, 1);  // scriptPath = null
        mv.visitInsn(ACONST_NULL);
        mv.visitVarInsn(ASTORE, 2);  // libDir = null
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ISTORE, 3);  // i = 0

        Label loopStart = new Label();
        Label loopEnd = new Label();
        mv.visitLabel(loopStart);
        mv.visitVarInsn(ILOAD, 3);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitInsn(ARRAYLENGTH);
        mv.visitJumpInsn(IF_ICMPGE, loopEnd);

        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ILOAD, 3);
        mv.visitInsn(AALOAD);
        mv.visitVarInsn(ASTORE, 4);  // arg = args[i]

        // if (arg.startsWith("--script="))
        mv.visitVarInsn(ALOAD, 4);
        mv.visitLdcInsn("--script=");
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "startsWith",
            "(Ljava/lang/String;)Z", false);
        Label notScript = new Label();
        mv.visitJumpInsn(IFEQ, notScript);
        mv.visitVarInsn(ALOAD, 4);
        mv.visitIntInsn(BIPUSH, 9);
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "substring",
            "(I)Ljava/lang/String;", false);
        mv.visitVarInsn(ASTORE, 1);
        Label loopContinue = new Label();
        mv.visitJumpInsn(GOTO, loopContinue);

        // if (arg.startsWith("--libdir="))
        mv.visitLabel(notScript);
        mv.visitVarInsn(ALOAD, 4);
        mv.visitLdcInsn("--libdir=");
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "startsWith",
            "(Ljava/lang/String;)Z", false);
        Label notLibdir = new Label();
        mv.visitJumpInsn(IFEQ, notLibdir);
        mv.visitVarInsn(ALOAD, 4);
        mv.visitIntInsn(BIPUSH, 9);
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "substring",
            "(I)Ljava/lang/String;", false);
        mv.visitVarInsn(ASTORE, 2);

        mv.visitLabel(notLibdir);
        mv.visitLabel(loopContinue);
        mv.visitIincInsn(3, 1);
        mv.visitJumpInsn(GOTO, loopStart);
        mv.visitLabel(loopEnd);

        // if scriptPath == null -> fall through to original main()
        mv.visitVarInsn(ALOAD, 1);
        mv.visitJumpInsn(IFNULL, originalStart);

        // Collect extraArgs after "--"
        mv.visitInsn(ICONST_0);
        mv.visitTypeInsn(ANEWARRAY, "java/lang/String");
        mv.visitVarInsn(ASTORE, 3);
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ISTORE, 4);
        Label eaStart = new Label();
        Label eaDone = new Label();
        mv.visitLabel(eaStart);
        mv.visitVarInsn(ILOAD, 4);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitInsn(ARRAYLENGTH);
        mv.visitJumpInsn(IF_ICMPGE, eaDone);

        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ILOAD, 4);
        mv.visitInsn(AALOAD);
        mv.visitLdcInsn("--");
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/String", "equals",
            "(Ljava/lang/Object;)Z", false);
        Label notDash = new Label();
        mv.visitJumpInsn(IFEQ, notDash);

        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ILOAD, 4);
        mv.visitInsn(ICONST_1);
        mv.visitInsn(IADD);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitInsn(ARRAYLENGTH);
        mv.visitMethodInsn(INVOKESTATIC, "java/util/Arrays", "copyOfRange",
            "([Ljava/lang/Object;II)[Ljava/lang/Object;", false);
        mv.visitTypeInsn(CHECKCAST, "[Ljava/lang/String;");
        mv.visitVarInsn(ASTORE, 3);
        mv.visitJumpInsn(GOTO, eaDone);

        mv.visitLabel(notDash);
        mv.visitIincInsn(4, 1);
        mv.visitJumpInsn(GOTO, eaStart);
        mv.visitLabel(eaDone);

        // Create {cls} and run script
        mv.visitTypeInsn(NEW, "com/pnfsoftware/jeb/{cls}");
        mv.visitInsn(DUP);
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitVarInsn(ALOAD, 2);
        mv.visitVarInsn(ALOAD, 3);
        mv.visitMethodInsn(INVOKESPECIAL, "com/pnfsoftware/jeb/{cls}", "<init>",
            "(ZLjava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V", false);
        mv.visitVarInsn(ASTORE, 4);

        mv.visitVarInsn(ALOAD, 4);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKEVIRTUAL, "com/pnfsoftware/jeb/{cls}", "initialize",
            "([Ljava/lang/String;)V", false);

        mv.visitVarInsn(ALOAD, 4);
        mv.visitMethodInsn(INVOKEVIRTUAL, "com/pnfsoftware/jeb/{cls}", "start",
            "()V", false);

        mv.visitVarInsn(ALOAD, 4);
        mv.visitMethodInsn(INVOKEVIRTUAL, "com/pnfsoftware/jeb/{cls}", "stop",
            "()V", false);

        mv.visitInsn(RETURN);

        // No --script= -> original main() code starts here (fall through)
        mv.visitLabel(originalStart);
        // Original bytecode follows via delegating MethodVisitor
    }}
}}
'''


def cmd_patch(ctx: CmdContext):
    """Patch jeb.jar Launcher.class to restore --script= support."""
    args, config = ctx.args, ctx.config
    log.debug("cmd_patch: starting")
    import subprocess as sp
    import shutil

    jeb_dir = config.get("jeb", {}).get("install_dir", "")

    if not os.path.isdir(jeb_dir):
        _log_err(f"JEB install directory not found: {jeb_dir}")
        return

    jar_path = os.path.join(jeb_dir, "bin", "app", "jeb.jar")
    bak_path = jar_path + ".bak"

    # Check if already patched
    if _opt(args, 'status', False):
        has_script = _is_jar_patched(jeb_dir)
        has_backup = os.path.isfile(jar_path + ".bak")
        if has_script and has_backup:
            _log_ok("--script= supported (patched)")
        elif has_script:
            _log_ok("--script= supported (native)")
        else:
            _log_info("--script= NOT supported (patch required)")
        return

    # Detect runner class
    cls_name, jeb_ver = _find_runner_class(jeb_dir, config)
    if not cls_name:
        return

    # Check if already has --script= support
    if _is_jar_patched(jeb_dir):
        if not _opt(args, 'force', False):
            _log_ok("--script= already supported")
            _log_info("Use --force to re-patch")
            return
        # Restore from backup first if re-patching
        if os.path.isfile(bak_path):
            _log_info("Restoring from backup before re-patching...")
            shutil.copy2(bak_path, jar_path)

    # Backup original
    if not os.path.isfile(bak_path):
        shutil.copy2(jar_path, bak_path)
        _log_ok(f"Backup: {bak_path}")

    # Generate LauncherPatcher.java
    patcher_src = os.path.join(jeb_dir, "LauncherPatcher.java")
    source = _PATCHER_TEMPLATE.format(cls=cls_name, ver=jeb_ver)
    with open(patcher_src, "w", encoding="utf-8") as f:
        f.write(source)
    _log_ok(f"Generated: {patcher_src}")

    java_bin, javac_bin, jar_bin, _ = _java_tools(config)
    cp_sep = ";" if sys.platform == "win32" else ":"
    cp = os.path.join("bin", "app", "*")

    # Step 1: Compile LauncherPatcher.java
    _log_info("Compiling LauncherPatcher.java...")
    try:
        sp.check_call(
            [javac_bin, "-cp", cp, "LauncherPatcher.java"],
            cwd=jeb_dir, timeout=60,
            stdout=sp.DEVNULL, stderr=sp.PIPE)
    except sp.CalledProcessError as e:
        _log_err(f"Compilation failed: {e.stderr.decode() if e.stderr else ''}")
        return
    except FileNotFoundError:
        _log_err(f"javac not found: {javac_bin}")
        return

    # Step 2: Run LauncherPatcher
    _log_info("Running LauncherPatcher...")
    try:
        result = sp.run(
            [java_bin, "-cp", cp + cp_sep + ".", "LauncherPatcher"],
            cwd=jeb_dir, timeout=60,
            capture_output=True, text=True)
        if result.stdout:
            for line in result.stdout.strip().splitlines():
                print(f"  {line}")
        if result.returncode != 0:
            _log_err(f"Patcher failed: {result.stderr}")
            return
    except Exception as e:
        _log_err(f"Patcher execution failed: {e}")
        return

    # Step 3: Apply patch to jeb.jar
    _log_info("Applying patch to jeb.jar...")
    patch_class = os.path.join(jeb_dir, "patch_out", "com", "pnfsoftware", "jeb", "Launcher.class")
    if not os.path.isfile(patch_class):
        _log_err("Patched Launcher.class not found in patch_out/")
        return

    try:
        sp.check_call(
            [jar_bin, "uf", os.path.join("bin", "app", "jeb.jar"),
             "-C", "patch_out", "com/pnfsoftware/jeb/Launcher.class"],
            cwd=jeb_dir, timeout=30)
        _log_ok("Patch applied to jeb.jar")
    except Exception as e:
        _log_err(f"jar uf failed: {e}")
        _log_info(f"Restore with: copy {bak_path} {jar_path}")
        return

    # Cleanup
    for f in [patcher_src,
              os.path.join(jeb_dir, "LauncherPatcher.class")]:
        if os.path.isfile(f):
            os.remove(f)
    patch_out = os.path.join(jeb_dir, "patch_out")
    if os.path.isdir(patch_out):
        shutil.rmtree(patch_out)

    if sys.platform == "win32":
        launcher = "jeb_wincon.bat"
    elif sys.platform == "darwin":
        launcher = "jeb_macos.sh"
    else:
        launcher = "jeb_linux.sh"
    _log_ok(f"Done! {launcher} -c --script=... is now available")
    _log_info(f"  Restore: jeb-cli unpatch")


def cmd_unpatch(ctx: CmdContext):
    """Restore original jeb.jar from backup."""
    args, config = ctx.args, ctx.config
    log.debug("cmd_unpatch: restoring backup")
    import shutil

    jeb_dir = config.get("jeb", {}).get("install_dir", "")
    jar_path = os.path.join(jeb_dir, "bin", "app", "jeb.jar")
    bak_path = jar_path + ".bak"

    if not os.path.isfile(bak_path):
        _log_err("No backup found: " + bak_path)
        return

    shutil.copy2(bak_path, jar_path)
    _log_ok(f"Restored: {jar_path}")
    _log_info("jeb.jar is back to original (unpatched)")


def cmd_merge(ctx: CmdContext):
    """Merge split APKs into a single APK using APKEditor."""
    args, config, config_path = ctx.args, ctx.config, ctx.config_path
    log.debug("cmd_merge: input=%s", args.input)
    import subprocess as sp
    jar, java_path = _resolve_apkeditor(config)
    if not jar:
        return

    input_path = os.path.abspath(args.input)
    if not os.path.exists(input_path):
        _log_err(f"Input not found: {input_path}")
        return

    # Hint: merge expects a directory of split APKs or XAPK/APKS file, not individual APK files
    if os.path.isfile(input_path) and input_path.lower().endswith(".apk"):
        parent = os.path.dirname(input_path)
        siblings = [f for f in os.listdir(parent) if f.lower().endswith(".apk")]
        if len(siblings) > 1:
            _log_warn(f"Input is an APK file. merge expects a split-APK directory or XAPK/APKS file.")
            _log_info(f"Try: merge {parent}")
            return

    # Determine output path: {package_name}_merged.apk
    out = _opt(args, 'out')
    if not out:
        pkg_name = _extract_package_name(input_path)
        if pkg_name:
            out_name = pkg_name + "_merged.apk"
        elif os.path.isdir(input_path):
            out_name = os.path.basename(input_path) + "_merged.apk"
        else:
            out_name = os.path.splitext(os.path.basename(input_path))[0] + "_merged.apk"
        out = os.path.join(os.path.dirname(input_path), out_name)
    out = os.path.abspath(out)

    # Run APKEditor merge
    cmd = [java_path, "-jar", jar, "m", "-i", input_path, "-o", out]
    _log_info(f"Merging: {os.path.basename(input_path)} → {os.path.basename(out)}")

    try:
        result = sp.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode != 0:
            _log_err(f"APKEditor merge failed (exit {result.returncode})")
            if result.stderr:
                print(result.stderr[:500])
            return
    except FileNotFoundError:
        _log_err(f"Java not found: {java_path}")
        return
    except sp.TimeoutExpired:
        _log_err("APKEditor merge timed out (300s)")
        return

    if not os.path.isfile(out):
        _log_err("Merge completed but output file not found")
        return

    size_mb = os.path.getsize(out) / (1024 * 1024)
    log.debug("cmd_merge: output=%s size=%.1fMB", out, size_mb)
    _log_ok(f"Merged: {out} ({size_mb:.1f}MB)")

    # --start: auto-start JEB analysis
    if _opt(args, 'start', False) and config_path:
        from .instance import cmd_start, _SimpleArgs  # lazy import to avoid circular
        _log_info("Starting JEB analysis on merged APK...")
        start_args = _SimpleArgs(
            binary=out, force=False, fresh=False,
            project_dir=None, xmx=_opt(args, 'xmx'))
        cmd_start(CmdContext(args=start_args, config=config, config_path=config_path))

    # Clear args.out to prevent _write_output from overwriting the merged APK.
    # merge's --out is the APK output path, not a text output path.
    args.out = None

    return {"merged_path": out, "size_mb": round(size_mb, 1)}
